### ISSUE TITLE
https://developer.yammer.com/api/realtime.html - BROKEN

### ISSUE THREAD

**Issue by gr-nanda** [oscarrenalias/yammer-push-api-client-node#1]
Hi - I could see this link is broken. Could someone provide me the correct url where I can find the documentation of node.js Yammer client API.

regards.
Nanda

**Comment by oscarrenalias** [comment]
A quick google took me to this page: https://developer.yammer.com/realtime/.

I'll fix in it in the README file, thanks.

**Comment by oscarrenalias** [comment]
Fixed.

**Comment by gr-nanda** [comment]
Hi - similarly, the links in the below paragraph also broken.

---

Features

## The module supports reading real-time data with the API from three different enpoints: messages (or rather, the All Company feed), topics and groups. The endpoint selection is via the second parameter object provided to the YammerPushAPI constructor; use values "all", "topics" and "groups" for the "type" key.

What I am looking at is, an API for the the client which has been created where I can refer at the methods available to call Yammer. Do you have created one? Please let me know if my question is not clear.

**Comment by oscarrenalias** [comment]
I think the README file says that there's an example under the samples/ folder. Have you seen this: https://github.com/oscarrenalias/yammer-push-api-client-node/blob/master/samples/testapp.js ?

Remember do to "npm install" from the samples folder so that you get the most recent version of the module installed automatically, otherwise it's not going to work.

There have been some changes to the API in the last couple of weeks so it may not work :-O... Let me know if that's the case.
